version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: facebookwall
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
volumes:
  pgdata:
